places = [{"placeName":"Mariott Marquis","descrip":"The Hunger Games was filmed here. The scenes where the Tributes were training took place here. ","latitude":33.761581,"longitude":-84.384956},
{"placeName":"Overlook Hotel","descrip":"The Shining was filmed here.","latitude":40.380779,"longitude":-105.51915},
{"placeName":"66 Perry St","descrip":"Sex and the City was filmed here. This is famously known as Carrie's New York Apartment.","latitude":40.73527,"longitude":-74.0038},
{"placeName":"Rocky Steps","descrip":"The infamous, triumphant scene of the movie Rocky was filmed here. It is also the entrance to the Phildelphia Mueseum of Art.","latitude":39.962631,"longitude":-75.177673},
{"placeName":"Chippewa Square","descrip":"Forest Gump was filmed here. This is where the park bench where Forest sits to tell his story is located.","latitude":32.069611,"longitude":-81.092781},
{"placeName":"Emory University Briarcliff Campus","descrip":"This location is seen in Stranger Things as the Hawkins Laboratory.","latitude":33.7882,"longitude":-84.33955},
{"placeName":"Mystic Grill","descrip":"Vampire Diaries was filmed here. Mystic Grill is one of the main sets for the show along with the surrounding town that is really called Mystic Falls.","latitude":33.5971,"longitude":-83.85992},
{"placeName":"Edgartown, Massachusetts","descrip":"Jaws the movie was filmed here. Edgartown is a small beach town in Martha's Vineyard.","latitude":41.39138,"longitude":-70.5196},
{"placeName":"The Prince","descrip":"New Girl is filmed here. This location is Nick's Bar in the show.","latitude":34.05949,"longitude":-118.29505},
{"placeName":"Multnomah Falls","descrip":"Twilight was filmed here. The movie's lush green scenes with Bella and Edward took place here.","latitude":45.53949,"longitude":-122.217163},
{"placeName":"McGee's Pub","descrip":"How I Met Your Mother was filmed here. This is a prominent set in the show known as McClarens Bar.","latitude":40.76482,"longitude":-73.98299},
{"placeName":"Boone Hall Plantation","descrip":"The Notebook was filmed here. The plantation was the set of the Allie Hamilton's summer home in the film.","latitude":32.85537,"longitude":-79.816658},
{"placeName":"Griffith Observatory","descrip":"La La Land was filmed here. This is was home to one of the most iconic dancing scenes of the movie.","latitude":34.11827,"longitude":-118.3004},
{"placeName":"Alfred Rosenheim Mansion","descrip":"American Horror Story season 1 ","latitude":34.05013,"longitude":-118.31723},
{"placeName":"Friends Apartment","descrip":"This location is famously known as the Friends Apartment from the show sitcom Friends. It appears in the show's transitions.","latitude":40.732281,"longitude":-74.005203},
{"placeName":"Mountain Lake Lodge","descrip":"This lodge was featured in Dirty Dancing as the Kellerman Resort.","latitude":37.35526,"longitude":-80.53689},
{"placeName":"Metropolitan Museum of Art","descrip":"The steps at the Metropolitan Museum of Art is a staple scene in the show Gossip Girl. This is where Blair Waldorf would have lunch in the show.","latitude":40.62433,"longitude":-74.02475},
{"placeName":"3828 Piermont Drive","descrip":"This is Walter White's house from Breaking Bad. ","latitude":35.126122,"longitude":-106.53653},
{"placeName":"The Firehouse on Tribeca","descrip":"This Firehouse in New York is seen on the movie Ghostbusters.","latitude":40.71976074,"longitude":-74.00663386},
{"placeName":"Greystone Mansion","descrip":"Episodes of Gilmore Girl was shot here. Its where many of Rory Gilmore's school scenes were shot.","latitude":34.09246101,"longitude":-118.4012774}]
